### ISSUE TITLE
Swagger does not pick up django-rest-registration endpoints.

### ISSUE THREAD

**Issue by polinom** [szopu/django-rest-registration#7] opened 2018-02-22 03:55 UTC
So I did setup everything like we you have here in example, and it seems like `django-rest-swagger` does not pick endpoints. 

Here are my urls:

```
from django.conf import settings
from django.urls import path, re_path, include, reverse_lazy
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import RedirectView
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views
from .users.views import UserViewSet, UserCreateViewSet

from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='Luken API')

router = DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'users', UserCreateViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('rest_registration.api.urls')),
    path('api/v1/', include(router.urls)),
    path('api/swagger/', schema_view),

    re_path(r'^$', RedirectView.as_view(url=reverse_lazy('api-root'), permanent=False)),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

Here is the result. 

![screen](https://cdn.pbrd.co/images/H8LihZh.png)

If you notice accounts are not being displayed.

**Comment by szopu** [comment] 2018-02-22 13:34
I see on the screenshot that there is an error (on the right bottom). This usually indicates that rest-swagger had some problem when extracting the schema - usually this indicates some misconfiguration on the server side.
Is there any stacktrace anywhere showing any problems? It could be in server output, or it could be sent in the server response. Maybe something is visible in your browser developer tools?

BTW: is using `reverse_lazy('...')` in `urls.py` valid? Also I don't see `'api-root'` defined anywhere. And why you didn't put rest-registration urls under `/api/` prefix?

**Comment by polinom** [comment] 2018-02-22 15:51
Yeah, I have that error only on my local, but it's not related to the fact that I don't see endpoints. 
On server I actually don't have error I can share url with you here: 

https://luken-qa.herokuapp.com/api-docs/

Also I don't see any traceback on my server. Everything is clean. It's a brand new project so there is is not a lot's of settings. It looks pretty much like your example app except for the fact that it's running in docker container. 

Btw, I did put it initially under under `/api/` but this had the same issue. 

Not sure what do you mean by `api-root`. You don't have that in example app as well.

**Comment by szopu** [comment] 2018-02-23 18:55
I meant that you're using `reverse_lazy('api-root')` but there is no url with name `api-root` in your `urls.py`, so I'm not sure what it would resolve to.

I also can't reproduce the bug in any way... I even upgraded my example project to newest `django-rest-swagger` version. There are some problems about the serializer schema not showing but all the endpoints are detected and you can 'test' them.
Could you send me the versions of packages you're using (for instance, the output of `pip freeze`) and your `settings.py` file?

Under the URL you sent me there is currently following message:

    400 : ["The schema generator did not return a schema Document"] https://luken-qa.herokuapp.com/api-docs/?format=openapi

**Comment by polinom** [comment] 2018-02-24 02:08
Hey, @szopu I figured out my problem.

```
400 : ["The schema generator did not return a schema Document"] https://luken-qa.herokuapp.com/api-docs/?format=openapi

```

You see it because you are not authenticated. When you authenticated you can see all the urls properly. 

I still feel like It integrates purely with swagger. For example when I open an endpoint it does not provide fields  that can be filled. Also it does not generate a proper curl command. I think we can have to implement coreapi chemas so it picks up fields of the Serializers as well.

**Comment by szopu** [comment] 2018-02-24 22:38
This is strange, I could access the endpoints even when I was not logged in. Maybe you are using some global permission class in your settings? Anyway...

Yes, I think there is a problem with new versions of `django-rest-swagger` having problem with extracting the schema from the view. I will create issue for that and work on it. I noticed this some time ago, but I hoped I will fix it in the meantime and gave it low priority. But it looks that other people are using this project with `django-rest-swagger` so I will have more motivation to fix it :smile: 

PS: Actually the view function is transformed via `api_view` decorator into an `ApiView` subclass and then converted back to function with the `as_view()` class method. I think the API around that changed in some way and that is the reason why it does not work now.

**Comment by polinom** [comment] 2018-02-26 15:29
@szopu So if it's happening how you describe it. It turns in to `ApiView `, than it makes sence that it does not work, because `ApiView ` does not know about `serializer`, and it seems like auto schema generation take info about fields form serializer of a `view/viewset` .

**Comment by szopu** [comment] 2018-02-26 16:09
> because `ApiView` does not know about `serializer`

This is not the case, at least not for all views. For some views I added custom `serializer_class_getter` decorator which is replacing the `get_serializer_class` method (which should also affect `get_serializer` method) into the source class of the view. So the schema should be able to retrieve it, but it is not doing it for some reason and the schema does not show up on the swagger page.

In other views I use old method of passing the information about the schema via the YAML config in the docstring, which worked in older versions of `django-rest-swagger` but it does not seem to work now. So when I will figure out how to pass the information about serializer properly in the first case I will apply the changes to the other views.

**Comment by szopu** [comment] 2018-02-27 09:29
@polinom if you don't mind I will close this issue.

**Comment by polinom** [comment] 2018-02-27 13:58
@szopu I don't mind at all. 
Thanks for addressing all this last issues in such an urgent manner. I very appreciate it!

**Closed** 2018-02-27 13:58 UTC
