### ISSUE TITLE
Logout view does not work for token auth

### ISSUE THREAD

**Issue by PotatoDrug** [szopu/django-rest-registration#16] opened 2018-04-01 08:55 UTC
Token is not deleted and still available for use after receiving `'Logout successful'` from logout view.

**Comment by szopu** [comment] 2018-04-01 20:32
I don't think this should be an expected behavior. Let's imagine following scenario:
1. The user may log on with a token on different machines. The same token is used because of the way the `Token` model is defined - it should be with the user in 1-1 relation.
2. Then he logs out on one machine, revoking the token
3. The user will get HTTP 401 on the other machine because the token he is using is already revoked but he didn't log out on this machine.

My idea is to add an optional `revoke_token` option which can be sent in the POST payload (as JSON, it would be something like this: `{"revoke_token": true}` ). What do you think about that?

**Comment by PotatoDrug** [comment] 2018-04-02 04:02
Ah I see, adding the revoke token option definitely makes more sense.

**Comment by szopu** [comment] 2018-04-02 11:12
I merged your PR, it will be released in next version ( `0.3.8` ).

**Closed by szopu** 2018-04-02 11:12 UTC
